
GET http://localhost:4001/api/minions HTTP/1.1

###

GET http://localhost:4001/api/minions/5 HTTP/1.1

###

POST http://localhost:4001/api/minions HTTP/1.1
content-type: application/json 

{
    "name": "Filipin",
    "title": "The Guard",
    "salary": "10000",
    "weaknesses": "Women"
}

###

POST http://localhost:4001/api/minions HTTP/1.1
Content-Type: application/json 

{
    "name": "Negrin",
    "title": "Snatcher",
    "salary": "30000",
    "weaknesses": "Honesty"
}

###

PUT http://localhost:4001/api/minions/1 HTTP/1.1
Content-Type: application/json 

{
    "name": "Edgardo",
    "title": "Future Paradigm Specialist",
    "weaknesses": "Everything",
    "salary": 10000
}

###

DELETE http://localhost:4001/api/minions/1 HTTP/1.1

###
#test for work API

GET http://localhost:4001/api/minions/5/work HTTP/1.1

###

GET http://localhost:4001/api/work HTTP/1.1

###
 
POST http://localhost:4001/api/minions/1/work HTTP/1.1
Content-Type: application/json

{
    "title":,
    "description":,
    "hours":,
    "minionId":
}

###

POST http://localhost:4001/api/minions/1/work/1 HTTP/1.1
Content-Type: application/json

{
    "title":,
    "description":,
    "hours":,
    "minionId":
}